# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

panelSDE <- function(observed, parameterTable) {
    .Call(`_psydiff_panelSDE`, observed, parameterTable)
}

setParameterValues <- function(parameterTable, parameterValues, parameterLabels) {
    invisible(.Call(`_psydiff_setParameterValues`, parameterTable, parameterValues, parameterLabels))
}

getParameterValues <- function(panelSDEModel) {
    .Call(`_psydiff_getParameterValues`, panelSDEModel)
}

setParameterTable <- function(parameterTable, parameterList, person) {
    invisible(.Call(`_psydiff_setParameterTable`, parameterTable, parameterList, person))
}

getSigmaPoints <- function(m, A, covarianceIsRoot, c) {
    .Call(`_psydiff_getSigmaPoints`, m, A, covarianceIsRoot, c)
}

getMeanWeights <- function(n, alpha, beta, kappa) {
    .Call(`_psydiff_getMeanWeights`, n, alpha, beta, kappa)
}

getWMatrix <- function(meanWeights, covWeights) {
    .Call(`_psydiff_getWMatrix`, meanWeights, covWeights)
}

computeMeanFromSigmaPoints <- function(sigmaPoints, meanWeights) {
    .Call(`_psydiff_computeMeanFromSigmaPoints`, sigmaPoints, meanWeights)
}

getAFromSigmaPoints <- function(sigmaPoints, meanWeights, c) {
    .Call(`_psydiff_getAFromSigmaPoints`, sigmaPoints, meanWeights, c)
}

computePFromSigmaPoints <- function(sigmaPoints, meanWeights, c) {
    .Call(`_psydiff_computePFromSigmaPoints`, sigmaPoints, meanWeights, c)
}

getPhi <- function(squareMatrix) {
    .Call(`_psydiff_getPhi`, squareMatrix)
}

predictMu <- function(Y_, meanWeights) {
    .Call(`_psydiff_predictMu`, Y_, meanWeights)
}

predictS <- function(Y_, W, R) {
    .Call(`_psydiff_predictS`, Y_, W, R)
}

predictC <- function(sigmaPoints, Y_, W) {
    .Call(`_psydiff_predictC`, sigmaPoints, Y_, W)
}

computeK <- function(C, S) {
    .Call(`_psydiff_computeK`, C, S)
}

updateM <- function(m_, K, residual) {
    .Call(`_psydiff_updateM`, m_, K, residual)
}

updateP <- function(P_, K, S) {
    .Call(`_psydiff_updateP`, P_, K, S)
}

computeIndividualM2LL <- function(nObservedVariables, rawData, expectedMeans, expectedCovariance) {
    .Call(`_psydiff_computeIndividualM2LL`, nObservedVariables, rawData, expectedMeans, expectedCovariance)
}

rcpparma_hello_world <- function() {
    .Call(`_psydiff_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_psydiff_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_psydiff_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_psydiff_rcpparma_bothproducts`, x)
}

